feature#176
Scout-Association-of-Japan/DX-promotion-guidelines pull request #177
Opened 2022-05-03 01:29 UTC by caffisenna

## 📝 関連issue / Related Issues

- close #176

## ⛏ 変更内容 / Details of Changes

- Meetの共同主催者設定方法を新設
- 録画機能が終了したことによる表記修正

2022-05-03 01:41 UTC, 07JP27 requested changes

2022-05-03 01:41 UTC, 07JP27 commented on docs/web-meeting-guide/meet/GoogleMeet-adv.md
> +Meetで共同主催者が設定できるようになりました。<br>
「できるようになった」はある特定時点からの状態移動で、見るタイミングに依って解釈が異なるので「できます」で良いと思います。

2022-05-03 01:41 UTC, 07JP27 commented on docs/web-meeting-guide/meet/GoogleMeet-co-hosts.md
> +共同主催者を設定すると以下のようなことができます。ミーティングの主催者が欠席したり、遅刻する場合でもミーティングをスムーズに運営することができるようになります。
```suggestion
共同主催者を設定するとミーティングの主催者が欠席したり、遅刻する場合でもミーティングをスムーズに運営することができるようになります。
具体的には共同主催者は以下の操作ができます。
```

2022-05-06 02:41 UTC, caffisenna commented
一端取り下げまーす (requirements.txt を先行していじるので)

2022-05-06 02:41 UTC, closed without merging