Add meet guide
Scout-Association-of-Japan/DX-promotion-guidelines pull request #29
Opened 2020-08-30 12:55 UTC by caffisenna

## 📝 関連issue / Related Issues

- close #23 

## ⛏ 変更内容 / Details of Changes

- google siteに掲載していたMeetの使い方をmd形式に移植
- Meet記事のmd化に伴ったリンク修正
- その他のページでテーブルが崩壊していたものを修正

2020-08-30 13:09 UTC, 07JP27 requested changes

2020-08-30 13:09 UTC, 07JP27 commented on web-meeting-guide/meet/GoogleMeet-smartphone.md
> +- Googleアカウントを持っていること(参加者は通常のGoogleアカウントでOKです / 会議の主催にはG Suiteのアカウントが必須です)
現在はG suiteアカウントが必須ではないかと思います。

2020-08-30 13:40 UTC, caffisenna commented on web-meeting-guide/meet/GoogleMeet-smartphone.md
> +- Googleアカウントを持っていること(参加者は通常のGoogleアカウントでOKです / 会議の主催にはG Suiteのアカウントが必須です)
`Googleアカウントを持っていること` の表記に修正します

2020-09-01 23:26 UTC, 07JP27 approved these changes

2020-09-01 23:26 UTC, merged

2020-09-01 23:52 UTC, caffisenna commented
mergeありがとうございます